version: 0.2

phases:
  pre_build:
    commands:
      - npm install --unsafe-perm

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 cp --recursive ./public s3://testbucket5356
