version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      # - echo "Retrieving secret from AWS Secrets Manager..."
      # - |
      #   SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --region $AWS_REGION --query SecretString --output text)
      #   if [ $? -ne 0 ]; then
      #     echo "Failed to retrieve secret: $SECRET_NAME"
      #     exit 1
      #   fi

      #   # Parse the JSON object and extract key-value pairs
      #   KEYS=$(echo "$SECRET_VALUE" | jq -r 'keys | .[]')

      #   for key in $KEYS; do
      #     value=$(echo "$SECRET_VALUE" | jq -r ".$key")
      #     export "$key"="$value"
      #     echo "Loaded key $key into environment variable $value"
      #   done

      - npm install

  build:
    commands:
      - printenv
      - npm run build

  post_build:
    commands:
      - npm run deploy
      # - aws s3 cp --sse --recursive ./public s3://mycdnbucket2
