version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - yarn
  build:
    commands:
      -  yarn build
  post_build:
    commands:
      - aws s3 cp --recursive ./public s3://gatsbysitepoc 